# Generated by Django 5.1.2 on 2024-11-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='logo',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='nb_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
